### ISSUE TITLE
Store selection of colors and size

### ISSUE THREAD

**Issue by manland** [undless/bigoo#1]
Every time i come on the demo page i need to select my favorite colors and size ! So you have two choices : 
* Set **MY** preference by default
* Retain (probably in local storage) my preference

Has you want, but I can't imagine a world where this params are not by default

![selection_032](https://user-images.githubusercontent.com/1492516/41359515-f431847c-6f2a-11e8-850d-b0371dd10a93.png)

With all my love :heart_eyes: :kiss:

**Comment by undless** [comment]
Dear @manland ,

I arleady though about it. I will push this Local Storage Feature for you.
(And i will put a "reset" buton in case of design emergency...)

Cheers !
